spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pironeer
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: rb87568756

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect