spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pironeer
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      springframework:
        security: TRACE

jwt:
  secret: 0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF0123456789ABCDEF
  access-token-expiration: 3600000   # 1?? (ms)
  refresh-token-expiration: 1209600000 # 14? (ms)